/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.acuma.k.shuffler.tables.Game;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record6<Long, Long, Long, Integer, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game.id</code>.
     */
    public GameRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.game.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.game.event_id</code>.
     */
    public GameRecord setEventId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.game.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.game.winner_id</code>.
     */
    public GameRecord setWinnerId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.game.winner_id</code>.
     */
    public Long getWinnerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.game.index</code>.
     */
    public GameRecord setIndex(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.game.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.game.started_at</code>.
     */
    public GameRecord setStartedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.game.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.game.finished_at</code>.
     */
    public GameRecord setFinishedAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.game.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Integer, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Integer, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Game.GAME.ID;
    }

    @Override
    public Field<Long> field2() {
        return Game.GAME.EVENT_ID;
    }

    @Override
    public Field<Long> field3() {
        return Game.GAME.WINNER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Game.GAME.INDEX;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Game.GAME.STARTED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Game.GAME.FINISHED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getEventId();
    }

    @Override
    public Long component3() {
        return getWinnerId();
    }

    @Override
    public Integer component4() {
        return getIndex();
    }

    @Override
    public OffsetDateTime component5() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getFinishedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getEventId();
    }

    @Override
    public Long value3() {
        return getWinnerId();
    }

    @Override
    public Integer value4() {
        return getIndex();
    }

    @Override
    public OffsetDateTime value5() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getFinishedAt();
    }

    @Override
    public GameRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GameRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    @Override
    public GameRecord value3(Long value) {
        setWinnerId(value);
        return this;
    }

    @Override
    public GameRecord value4(Integer value) {
        setIndex(value);
        return this;
    }

    @Override
    public GameRecord value5(OffsetDateTime value) {
        setStartedAt(value);
        return this;
    }

    @Override
    public GameRecord value6(OffsetDateTime value) {
        setFinishedAt(value);
        return this;
    }

    @Override
    public GameRecord values(Long value1, Long value2, Long value3, Integer value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(Long id, Long eventId, Long winnerId, Integer index, OffsetDateTime startedAt, OffsetDateTime finishedAt) {
        super(Game.GAME);

        setId(id);
        setEventId(eventId);
        setWinnerId(winnerId);
        setIndex(index);
        setStartedAt(startedAt);
        setFinishedAt(finishedAt);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(ru.acuma.k.shuffler.tables.pojos.Game value) {
        super(Game.GAME);

        if (value != null) {
            setId(value.getId());
            setEventId(value.getEventId());
            setWinnerId(value.getWinnerId());
            setIndex(value.getIndex());
            setStartedAt(value.getStartedAt());
            setFinishedAt(value.getFinishedAt());
        }
    }
}
