/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.acuma.k.shuffler.tables.Game;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record8<Long, Long, JSONB, JSONB, Integer, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game.id</code>.
     */
    public GameRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.game.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.game.event_id</code>.
     */
    public GameRecord setEventId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.game.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.game.team_a</code>.
     */
    public GameRecord setTeamA(JSONB value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.game.team_a</code>.
     */
    public JSONB getTeamA() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.game.team_b</code>.
     */
    public GameRecord setTeamB(JSONB value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.game.team_b</code>.
     */
    public JSONB getTeamB() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.game.index</code>.
     */
    public GameRecord setIndex(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.game.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.game.result</code>.
     */
    public GameRecord setResult(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.game.result</code>.
     */
    public String getResult() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.game.started_at</code>.
     */
    public GameRecord setStartedAt(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.game.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.game.finished_at</code>.
     */
    public GameRecord setFinishedAt(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.game.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, JSONB, JSONB, Integer, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, JSONB, JSONB, Integer, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Game.GAME.ID;
    }

    @Override
    public Field<Long> field2() {
        return Game.GAME.EVENT_ID;
    }

    @Override
    public Field<JSONB> field3() {
        return Game.GAME.TEAM_A;
    }

    @Override
    public Field<JSONB> field4() {
        return Game.GAME.TEAM_B;
    }

    @Override
    public Field<Integer> field5() {
        return Game.GAME.INDEX;
    }

    @Override
    public Field<String> field6() {
        return Game.GAME.RESULT;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return Game.GAME.STARTED_AT;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return Game.GAME.FINISHED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getEventId();
    }

    @Override
    public JSONB component3() {
        return getTeamA();
    }

    @Override
    public JSONB component4() {
        return getTeamB();
    }

    @Override
    public Integer component5() {
        return getIndex();
    }

    @Override
    public String component6() {
        return getResult();
    }

    @Override
    public OffsetDateTime component7() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime component8() {
        return getFinishedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getEventId();
    }

    @Override
    public JSONB value3() {
        return getTeamA();
    }

    @Override
    public JSONB value4() {
        return getTeamB();
    }

    @Override
    public Integer value5() {
        return getIndex();
    }

    @Override
    public String value6() {
        return getResult();
    }

    @Override
    public OffsetDateTime value7() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime value8() {
        return getFinishedAt();
    }

    @Override
    public GameRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GameRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    @Override
    public GameRecord value3(JSONB value) {
        setTeamA(value);
        return this;
    }

    @Override
    public GameRecord value4(JSONB value) {
        setTeamB(value);
        return this;
    }

    @Override
    public GameRecord value5(Integer value) {
        setIndex(value);
        return this;
    }

    @Override
    public GameRecord value6(String value) {
        setResult(value);
        return this;
    }

    @Override
    public GameRecord value7(OffsetDateTime value) {
        setStartedAt(value);
        return this;
    }

    @Override
    public GameRecord value8(OffsetDateTime value) {
        setFinishedAt(value);
        return this;
    }

    @Override
    public GameRecord values(Long value1, Long value2, JSONB value3, JSONB value4, Integer value5, String value6, OffsetDateTime value7, OffsetDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(Long id, Long eventId, JSONB teamA, JSONB teamB, Integer index, String result, OffsetDateTime startedAt, OffsetDateTime finishedAt) {
        super(Game.GAME);

        setId(id);
        setEventId(eventId);
        setTeamA(teamA);
        setTeamB(teamB);
        setIndex(index);
        setResult(result);
        setStartedAt(startedAt);
        setFinishedAt(finishedAt);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(ru.acuma.k.shuffler.tables.pojos.Game value) {
        super(Game.GAME);

        if (value != null) {
            setId(value.getId());
            setEventId(value.getEventId());
            setTeamA(value.getTeamA());
            setTeamB(value.getTeamB());
            setIndex(value.getIndex());
            setResult(value.getResult());
            setStartedAt(value.getStartedAt());
            setFinishedAt(value.getFinishedAt());
        }
    }
}
