/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.acuma.k.shuffler.tables.Team;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamRecord extends UpdatableRecordImpl<TeamRecord> implements Record4<Long, Long, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.team.id</code>.
     */
    public TeamRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.team.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.team.game_id</code>.
     */
    public TeamRecord setGameId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.team.game_id</code>.
     */
    public Long getGameId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.team.started_at</code>.
     */
    public TeamRecord setStartedAt(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.team.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.team.finished_at</code>.
     */
    public TeamRecord setFinishedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.team.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Team.TEAM.ID;
    }

    @Override
    public Field<Long> field2() {
        return Team.TEAM.GAME_ID;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return Team.TEAM.STARTED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Team.TEAM.FINISHED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGameId();
    }

    @Override
    public OffsetDateTime component3() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getFinishedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGameId();
    }

    @Override
    public OffsetDateTime value3() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getFinishedAt();
    }

    @Override
    public TeamRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TeamRecord value2(Long value) {
        setGameId(value);
        return this;
    }

    @Override
    public TeamRecord value3(OffsetDateTime value) {
        setStartedAt(value);
        return this;
    }

    @Override
    public TeamRecord value4(OffsetDateTime value) {
        setFinishedAt(value);
        return this;
    }

    @Override
    public TeamRecord values(Long value1, Long value2, OffsetDateTime value3, OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamRecord
     */
    public TeamRecord() {
        super(Team.TEAM);
    }

    /**
     * Create a detached, initialised TeamRecord
     */
    public TeamRecord(Long id, Long gameId, OffsetDateTime startedAt, OffsetDateTime finishedAt) {
        super(Team.TEAM);

        setId(id);
        setGameId(gameId);
        setStartedAt(startedAt);
        setFinishedAt(finishedAt);
    }

    /**
     * Create a detached, initialised TeamRecord
     */
    public TeamRecord(ru.acuma.k.shuffler.tables.pojos.Team value) {
        super(Team.TEAM);

        if (value != null) {
            setId(value.getId());
            setGameId(value.getGameId());
            setStartedAt(value.getStartedAt());
            setFinishedAt(value.getFinishedAt());
        }
    }
}
