version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${K_SHUFFLER_DB_NAME:localhost}
      POSTGRES_USER: ${K_SHUFFLER_DB_USER:localhost}
      POSTGRES_PASSWORD: ${K_SHUFFLER_DB_PASSWORD:localhost}
    ports:
      - "5432:5432"
