/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Event implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long           id;
    private Long           chatId;
    private JSONB          messages;
    private JSONB          kickerplayers;
    private String         status;
    private OffsetDateTime startedAt;
    private OffsetDateTime finishedAt;

    public Event() {}

    public Event(Event value) {
        this.id = value.id;
        this.chatId = value.chatId;
        this.messages = value.messages;
        this.kickerplayers = value.kickerplayers;
        this.status = value.status;
        this.startedAt = value.startedAt;
        this.finishedAt = value.finishedAt;
    }

    public Event(
        Long           id,
        Long           chatId,
        JSONB          messages,
        JSONB          kickerplayers,
        String         status,
        OffsetDateTime startedAt,
        OffsetDateTime finishedAt
    ) {
        this.id = id;
        this.chatId = chatId;
        this.messages = messages;
        this.kickerplayers = kickerplayers;
        this.status = status;
        this.startedAt = startedAt;
        this.finishedAt = finishedAt;
    }

    /**
     * Getter for <code>public.event.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.event.id</code>.
     */
    public Event setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.event.chat_id</code>.
     */
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.event.chat_id</code>.
     */
    public Event setChatId(Long chatId) {
        this.chatId = chatId;
        return this;
    }

    /**
     * Getter for <code>public.event.messages</code>.
     */
    public JSONB getMessages() {
        return this.messages;
    }

    /**
     * Setter for <code>public.event.messages</code>.
     */
    public Event setMessages(JSONB messages) {
        this.messages = messages;
        return this;
    }

    /**
     * Getter for <code>public.event.kickerplayers</code>.
     */
    public JSONB getKickerplayers() {
        return this.kickerplayers;
    }

    /**
     * Setter for <code>public.event.kickerplayers</code>.
     */
    public Event setKickerplayers(JSONB kickerplayers) {
        this.kickerplayers = kickerplayers;
        return this;
    }

    /**
     * Getter for <code>public.event.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.event.status</code>.
     */
    public Event setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.event.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>public.event.started_at</code>.
     */
    public Event setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Getter for <code>public.event.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return this.finishedAt;
    }

    /**
     * Setter for <code>public.event.finished_at</code>.
     */
    public Event setFinishedAt(OffsetDateTime finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Event (");

        sb.append(id);
        sb.append(", ").append(chatId);
        sb.append(", ").append(messages);
        sb.append(", ").append(kickerplayers);
        sb.append(", ").append(status);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(finishedAt);

        sb.append(")");
        return sb.toString();
    }
}
