/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Event implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long           id;
    private Long           groupId;
    private JSONB          members;
    private Integer        games;
    private OffsetDateTime startedAt;
    private OffsetDateTime finishedAt;

    public Event() {}

    public Event(Event value) {
        this.id = value.id;
        this.groupId = value.groupId;
        this.members = value.members;
        this.games = value.games;
        this.startedAt = value.startedAt;
        this.finishedAt = value.finishedAt;
    }

    public Event(
        Long           id,
        Long           groupId,
        JSONB          members,
        Integer        games,
        OffsetDateTime startedAt,
        OffsetDateTime finishedAt
    ) {
        this.id = id;
        this.groupId = groupId;
        this.members = members;
        this.games = games;
        this.startedAt = startedAt;
        this.finishedAt = finishedAt;
    }

    /**
     * Getter for <code>public.event.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.event.id</code>.
     */
    public Event setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.event.group_id</code>.
     */
    public Long getGroupId() {
        return this.groupId;
    }

    /**
     * Setter for <code>public.event.group_id</code>.
     */
    public Event setGroupId(Long groupId) {
        this.groupId = groupId;
        return this;
    }

    /**
     * Getter for <code>public.event.members</code>.
     */
    public JSONB getMembers() {
        return this.members;
    }

    /**
     * Setter for <code>public.event.members</code>.
     */
    public Event setMembers(JSONB members) {
        this.members = members;
        return this;
    }

    /**
     * Getter for <code>public.event.games</code>.
     */
    public Integer getGames() {
        return this.games;
    }

    /**
     * Setter for <code>public.event.games</code>.
     */
    public Event setGames(Integer games) {
        this.games = games;
        return this;
    }

    /**
     * Getter for <code>public.event.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>public.event.started_at</code>.
     */
    public Event setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Getter for <code>public.event.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return this.finishedAt;
    }

    /**
     * Setter for <code>public.event.finished_at</code>.
     */
    public Event setFinishedAt(OffsetDateTime finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Event (");

        sb.append(id);
        sb.append(", ").append(groupId);
        sb.append(", ").append(members);
        sb.append(", ").append(games);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(finishedAt);

        sb.append(")");
        return sb.toString();
    }
}
