/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Game implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long           id;
    private Long           eventId;
    private Integer        index;
    private OffsetDateTime startedAt;
    private OffsetDateTime finishedAt;

    public Game() {}

    public Game(Game value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.index = value.index;
        this.startedAt = value.startedAt;
        this.finishedAt = value.finishedAt;
    }

    public Game(
        Long           id,
        Long           eventId,
        Integer        index,
        OffsetDateTime startedAt,
        OffsetDateTime finishedAt
    ) {
        this.id = id;
        this.eventId = eventId;
        this.index = index;
        this.startedAt = startedAt;
        this.finishedAt = finishedAt;
    }

    /**
     * Getter for <code>public.game.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.game.id</code>.
     */
    public Game setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.game.event_id</code>.
     */
    public Long getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>public.game.event_id</code>.
     */
    public Game setEventId(Long eventId) {
        this.eventId = eventId;
        return this;
    }

    /**
     * Getter for <code>public.game.index</code>.
     */
    public Integer getIndex() {
        return this.index;
    }

    /**
     * Setter for <code>public.game.index</code>.
     */
    public Game setIndex(Integer index) {
        this.index = index;
        return this;
    }

    /**
     * Getter for <code>public.game.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>public.game.started_at</code>.
     */
    public Game setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Getter for <code>public.game.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return this.finishedAt;
    }

    /**
     * Setter for <code>public.game.finished_at</code>.
     */
    public Game setFinishedAt(OffsetDateTime finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Game (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(index);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(finishedAt);

        sb.append(")");
        return sb.toString();
    }
}
