/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Game implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long           id;
    private Long           eventId;
    private JSONB          teamA;
    private JSONB          teamB;
    private Integer        index;
    private String         result;
    private OffsetDateTime startedAt;
    private OffsetDateTime finishedAt;

    public Game() {}

    public Game(Game value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.teamA = value.teamA;
        this.teamB = value.teamB;
        this.index = value.index;
        this.result = value.result;
        this.startedAt = value.startedAt;
        this.finishedAt = value.finishedAt;
    }

    public Game(
        Long           id,
        Long           eventId,
        JSONB          teamA,
        JSONB          teamB,
        Integer        index,
        String         result,
        OffsetDateTime startedAt,
        OffsetDateTime finishedAt
    ) {
        this.id = id;
        this.eventId = eventId;
        this.teamA = teamA;
        this.teamB = teamB;
        this.index = index;
        this.result = result;
        this.startedAt = startedAt;
        this.finishedAt = finishedAt;
    }

    /**
     * Getter for <code>public.game.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.game.id</code>.
     */
    public Game setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.game.event_id</code>.
     */
    public Long getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>public.game.event_id</code>.
     */
    public Game setEventId(Long eventId) {
        this.eventId = eventId;
        return this;
    }

    /**
     * Getter for <code>public.game.team_a</code>.
     */
    public JSONB getTeamA() {
        return this.teamA;
    }

    /**
     * Setter for <code>public.game.team_a</code>.
     */
    public Game setTeamA(JSONB teamA) {
        this.teamA = teamA;
        return this;
    }

    /**
     * Getter for <code>public.game.team_b</code>.
     */
    public JSONB getTeamB() {
        return this.teamB;
    }

    /**
     * Setter for <code>public.game.team_b</code>.
     */
    public Game setTeamB(JSONB teamB) {
        this.teamB = teamB;
        return this;
    }

    /**
     * Getter for <code>public.game.index</code>.
     */
    public Integer getIndex() {
        return this.index;
    }

    /**
     * Setter for <code>public.game.index</code>.
     */
    public Game setIndex(Integer index) {
        this.index = index;
        return this;
    }

    /**
     * Getter for <code>public.game.result</code>.
     */
    public String getResult() {
        return this.result;
    }

    /**
     * Setter for <code>public.game.result</code>.
     */
    public Game setResult(String result) {
        this.result = result;
        return this;
    }

    /**
     * Getter for <code>public.game.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>public.game.started_at</code>.
     */
    public Game setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Getter for <code>public.game.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return this.finishedAt;
    }

    /**
     * Setter for <code>public.game.finished_at</code>.
     */
    public Game setFinishedAt(OffsetDateTime finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Game (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(teamA);
        sb.append(", ").append(teamB);
        sb.append(", ").append(index);
        sb.append(", ").append(result);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(finishedAt);

        sb.append(")");
        return sb.toString();
    }
}
