/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   telegramId;
    private String title;
    private JSONB  members;

    public GroupInfo() {}

    public GroupInfo(GroupInfo value) {
        this.id = value.id;
        this.telegramId = value.telegramId;
        this.title = value.title;
        this.members = value.members;
    }

    public GroupInfo(
        Long   id,
        Long   telegramId,
        String title,
        JSONB  members
    ) {
        this.id = id;
        this.telegramId = telegramId;
        this.title = title;
        this.members = members;
    }

    /**
     * Getter for <code>public.group_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.group_info.id</code>.
     */
    public GroupInfo setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.group_info.telegram_id</code>.
     */
    public Long getTelegramId() {
        return this.telegramId;
    }

    /**
     * Setter for <code>public.group_info.telegram_id</code>.
     */
    public GroupInfo setTelegramId(Long telegramId) {
        this.telegramId = telegramId;
        return this;
    }

    /**
     * Getter for <code>public.group_info.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.group_info.title</code>.
     */
    public GroupInfo setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>public.group_info.members</code>.
     */
    public JSONB getMembers() {
        return this.members;
    }

    /**
     * Setter for <code>public.group_info.members</code>.
     */
    public GroupInfo setMembers(JSONB members) {
        this.members = members;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupInfo (");

        sb.append(id);
        sb.append(", ").append(telegramId);
        sb.append(", ").append(title);
        sb.append(", ").append(members);

        sb.append(")");
        return sb.toString();
    }
}
