/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Team implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long           id;
    private Long           gameId;
    private OffsetDateTime startedAt;
    private OffsetDateTime finishedAt;

    public Team() {}

    public Team(Team value) {
        this.id = value.id;
        this.gameId = value.gameId;
        this.startedAt = value.startedAt;
        this.finishedAt = value.finishedAt;
    }

    public Team(
        Long           id,
        Long           gameId,
        OffsetDateTime startedAt,
        OffsetDateTime finishedAt
    ) {
        this.id = id;
        this.gameId = gameId;
        this.startedAt = startedAt;
        this.finishedAt = finishedAt;
    }

    /**
     * Getter for <code>public.team.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.team.id</code>.
     */
    public Team setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.team.game_id</code>.
     */
    public Long getGameId() {
        return this.gameId;
    }

    /**
     * Setter for <code>public.team.game_id</code>.
     */
    public Team setGameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    /**
     * Getter for <code>public.team.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>public.team.started_at</code>.
     */
    public Team setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Getter for <code>public.team.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return this.finishedAt;
    }

    /**
     * Setter for <code>public.team.finished_at</code>.
     */
    public Team setFinishedAt(OffsetDateTime finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Team (");

        sb.append(id);
        sb.append(", ").append(gameId);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(finishedAt);

        sb.append(")");
        return sb.toString();
    }
}
