/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.acuma.k.shuffler.tables.Event;
import ru.acuma.k.shuffler.tables.FlywaySchemaHistory;
import ru.acuma.k.shuffler.tables.Game;
import ru.acuma.k.shuffler.tables.GroupInfo;
import ru.acuma.k.shuffler.tables.Player;
import ru.acuma.k.shuffler.tables.Team;
import ru.acuma.k.shuffler.tables.UserInfo;
import ru.acuma.k.shuffler.tables.records.EventRecord;
import ru.acuma.k.shuffler.tables.records.FlywaySchemaHistoryRecord;
import ru.acuma.k.shuffler.tables.records.GameRecord;
import ru.acuma.k.shuffler.tables.records.GroupInfoRecord;
import ru.acuma.k.shuffler.tables.records.PlayerRecord;
import ru.acuma.k.shuffler.tables.records.TeamRecord;
import ru.acuma.k.shuffler.tables.records.UserInfoRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventRecord> EVENT_PKEY = Internal.createUniqueKey(Event.EVENT, DSL.name("event_pkey"), new TableField[] { Event.EVENT.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<GameRecord> GAME_PKEY = Internal.createUniqueKey(Game.GAME, DSL.name("game_pkey"), new TableField[] { Game.GAME.ID }, true);
    public static final UniqueKey<GroupInfoRecord> GROUP_INFO_PKEY = Internal.createUniqueKey(GroupInfo.GROUP_INFO, DSL.name("group_info_pkey"), new TableField[] { GroupInfo.GROUP_INFO.CHAT_ID }, true);
    public static final UniqueKey<PlayerRecord> PLAYER_PKEY = Internal.createUniqueKey(Player.PLAYER, DSL.name("player_pkey"), new TableField[] { Player.PLAYER.ID }, true);
    public static final UniqueKey<TeamRecord> TEAM_PKEY = Internal.createUniqueKey(Team.TEAM, DSL.name("team_pkey"), new TableField[] { Team.TEAM.ID }, true);
    public static final UniqueKey<UserInfoRecord> USER_INFO_PKEY = Internal.createUniqueKey(UserInfo.USER_INFO, DSL.name("user_info_pkey"), new TableField[] { UserInfo.USER_INFO.TELEGRAM_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EventRecord, GroupInfoRecord> EVENT__FK_EXISTS_CHAT = Internal.createForeignKey(Event.EVENT, DSL.name("fk_exists_chat"), new TableField[] { Event.EVENT.CHAT_ID }, Keys.GROUP_INFO_PKEY, new TableField[] { GroupInfo.GROUP_INFO.CHAT_ID }, true);
    public static final ForeignKey<GameRecord, EventRecord> GAME__FK_EXISTS_EVENT = Internal.createForeignKey(Game.GAME, DSL.name("fk_exists_event"), new TableField[] { Game.GAME.EVENT_ID }, Keys.EVENT_PKEY, new TableField[] { Event.EVENT.ID }, true);
    public static final ForeignKey<PlayerRecord, GroupInfoRecord> PLAYER__FK_EXISTS_CHAT = Internal.createForeignKey(Player.PLAYER, DSL.name("fk_exists_chat"), new TableField[] { Player.PLAYER.CHAT_ID }, Keys.GROUP_INFO_PKEY, new TableField[] { GroupInfo.GROUP_INFO.CHAT_ID }, true);
    public static final ForeignKey<PlayerRecord, UserInfoRecord> PLAYER__FK_EXISTS_USER = Internal.createForeignKey(Player.PLAYER, DSL.name("fk_exists_user"), new TableField[] { Player.PLAYER.USER_ID }, Keys.USER_INFO_PKEY, new TableField[] { UserInfo.USER_INFO.TELEGRAM_ID }, true);
    public static final ForeignKey<TeamRecord, GameRecord> TEAM__FK_EXISTS_GAME = Internal.createForeignKey(Team.TEAM, DSL.name("fk_exists_game"), new TableField[] { Team.TEAM.GAME_ID }, Keys.GAME_PKEY, new TableField[] { Game.GAME.ID }, true);
}
